# Generated by Django 3.1.1 on 2021-05-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210522_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('exhibitions', 'exhibitions'), ('theater', 'theater'), ('shows', 'shows')], max_length=255, verbose_name='category name'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('will visit', 'will visit'), ("won't visit", "won't visit"), ('already visited', 'already visited')], max_length=255, verbose_name='status name'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(choices=[('image', 'image'), ('music', 'music'), ('video', 'video')], max_length=255, verbose_name='type name'),
        ),
    ]
