# Generated by Django 3.1.1 on 2021-05-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210522_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('not selected', 'not selected'), ('will visit', 'will visit'), ("won't visit", "won't visit"), ('already visited', 'already visited')], default=('not selected', 'not selected'), max_length=255, verbose_name='status name'),
        ),
    ]
