# Generated by Django 3.1.1 on 2021-05-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210522_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(choices=[('not selected', 'not selected'), ('will visit', 'will visit'), ("won't visit", "won't visit"), ('already visited', 'already visited')], default='not selected', max_length=255, verbose_name='status name'),
        ),
    ]
