# Generated by Django 3.1.1 on 2021-05-24 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_auto_20210522_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitevent',
            name='event_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='visitevent',
            name='status_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.status'),
        ),
        migrations.AlterField(
            model_name='visitevent',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
