# Generated by Django 3.1.1 on 2021-05-24 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210524_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitevent',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.status'),
        ),
    ]
