# Generated by Django 3.1.1 on 2021-05-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210524_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmedia',
            name='url',
            field=models.FileField(upload_to='event_images/', verbose_name='url of a media file'),
        ),
    ]
