# Generated by Django 3.1.1 on 2021-04-02 04:01

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('account_login', models.CharField(max_length=30, unique=True, verbose_name='Логин аккаунта')),
                ('account_password', models.CharField(max_length=256, verbose_name='Пароль аккаунта')),
                ('account_email', models.CharField(max_length=30, unique=True, verbose_name='Почта аккаунта')),
                ('account_phone', models.CharField(max_length=12, verbose_name='Телефон аккаунта')),
                ('account_image', models.ImageField(upload_to='', verbose_name='Фото аккаунта')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
